# Generated by Django 5.1.4 on 2025-02-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_myuser_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="country",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
