# Generated by Django 5.1.4 on 2025-01-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Заголовок"),
                ),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "preview",
                    models.ImageField(
                        upload_to="posts/", verbose_name="Изображение"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="Признак публикации"
                    ),
                ),
                (
                    "number_views",
                    models.ImageField(
                        default=0,
                        upload_to="",
                        verbose_name="количество просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись в блоге",
                "verbose_name_plural": "Записи в блоге",
            },
        ),
    ]
