# Generated by Django 5.1.4 on 2024-12-26 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Телефонный номер необходимо вводить в формате '9999999999'",
                                regex="^\\+7\\d{10}",
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
            ],
            options={
                "verbose_name": "Контактное лицо",
                "verbose_name_plural": "Контактные лица",
            },
        ),
    ]
