# Generated by Django 5.1.4 on 2024-12-26 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Телефонный номер необходимо вводить в формате '9999999999'",
                        regex="^\\+7\\d{12}",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
